In [1]:
import pandas as pd

In [2]:
steam_reviews = pd.read_csv('steam_reviews.csv')

In [3]:
steam_reviews.head()

,date_posted,funny,helpful,hour_played,is_early_access_review,recommendation,review,title
0,2019-02-10,2,4,578,False,Recommended,&gt Played as German Reich&gt Declare war on B...,Expansion - Hearts of Iron IV: Man the Guns
1,2019-02-10,0,0,184,False,Recommended,yes.,Expansion - Hearts of Iron IV: Man the Guns
2,2019-02-07,0,0,892,False,Recommended,Very good game although a bit overpriced in my...,Expansion - Hearts of Iron IV: Man the Guns
3,2018-06-14,126,1086,676,False,Recommended,Out of all the reviews I wrote This one is pro...,Dead by Daylight
4,2017-06-20,85,2139,612,False,Recommended,Disclaimer I survivor main. I play games for f...,Dead by Daylight

In [4]:
steam_reviews = steam_reviews[['date_posted', 'funny', 'helpful', 'hour_played', 'recommendation', 'review', 'title']]

In [5]:
steam_reviews.head()

,date_posted,funny,helpful,hour_played,recommendation,review,title
0,2019-02-10,2,4,578,Recommended,&gt Played as German Reich&gt Declare war on B...,Expansion - Hearts of Iron IV: Man the Guns
1,2019-02-10,0,0,184,Recommended,yes.,Expansion - Hearts of Iron IV: Man the Guns
2,2019-02-07,0,0,892,Recommended,Very good game although a bit overpriced in my...,Expansion - Hearts of Iron IV: Man the Guns
3,2018-06-14,126,1086,676,Recommended,Out of all the reviews I wrote This one is pro...,Dead by Daylight
4,2017-06-20,85,2139,612,Recommended,Disclaimer I survivor main. I play games for f...,Dead by Daylight

In [8]:
steam_reviews['id'] = steam_reviews.index

In [9]:
steam_reviews.head()

,date_posted,funny,helpful,hour_played,recommendation,review,title,id
0,2019-02-10,2,4,578,Recommended,&gt Played as German Reich&gt Declare war on B...,Expansion - Hearts of Iron IV: Man the Guns,0
1,2019-02-10,0,0,184,Recommended,yes.,Expansion - Hearts of Iron IV: Man the Guns,1
2,2019-02-07,0,0,892,Recommended,Very good game although a bit overpriced in my...,Expansion - Hearts of Iron IV: Man the Guns,2
3,2018-06-14,126,1086,676,Recommended,Out of all the reviews I wrote This one is pro...,Dead by Daylight,3
4,2017-06-20,85,2139,612,Recommended,Disclaimer I survivor main. I play games for f...,Dead by Daylight,4

In [14]:
steam_reviews = steam_reviews.reindex(columns = ['id','title','date_posted','funny','helpful','hour_played','recommendation','review'])

In [15]:
steam_reviews.head()

,id,title,date_posted,funny,helpful,hour_played,recommendation,review
0,0,Expansion - Hearts of Iron IV: Man the Guns,2019-02-10,2,4,578,Recommended,&gt Played as German Reich&gt Declare war on B...
1,1,Expansion - Hearts of Iron IV: Man the Guns,2019-02-10,0,0,184,Recommended,yes.
2,2,Expansion - Hearts of Iron IV: Man the Guns,2019-02-07,0,0,892,Recommended,Very good game although a bit overpriced in my...
3,3,Dead by Daylight,2018-06-14,126,1086,676,Recommended,Out of all the reviews I wrote This one is pro...
4,4,Dead by Daylight,2017-06-20,85,2139,612,Recommended,Disclaimer I survivor main. I play games for f...

In [20]:
steam_reviews.isnull().any()

id                False
title             False
date_posted       False
funny             False
helpful           False
hour_played       False
recommendation    False
review            False
dtype: bool

In [19]:
steam_reviews['review'].fillna('Not shown', inplace = True)

In [21]:
steam_reviews.to_csv('steam_reviews_clean.csv', index = False)